### ISSUE TITLE
Directive attributes are hard to type in editor

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#10895]
While the new directive attributes feature is great, it feels like the editor experience needs a lot more review and polish. Trying to type them is quite a bizarre and hostile experience currently :)

Examples:

 * Try typing `<input @bind="@someText" @bind:ev`. It will prompt you to auto-complete `@bind:event`, which is perfect, but then if you press tab to accept the suggestion, it replaces what you just typed with `<input @bind="@someText" @bind=""`, which is not at all what you want. Note that it *only* does this if you've just typed out all of what I wrote here, and not if you go back and edit an existing `<input>`.
 * Try pasting this into a `.razor` file: `<input @bind="@someText" />`. For some reason it inserts a space between `@` and `bind`, so you get `<input @ bind="@someText" />`. Was this recently fixed? I remember hearing something about this.
 * Try typing `<div @bind` and then press the `=` character. For some reason it transforms what you typed into this: `<div bind-=""`. I know it's strange to try doing a `bind` on a `div`, but this still is an editor bug. Maybe it surfaces in other ways too.
 * While I was doing some of the above (don't remember what triggered it exactly), VS reported an exception. The log file contains a lot of entries like this:

```
  <entry>
    <record>1127</record>
    <time>2019/06/05 12:12:27.457</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: An entry with the same key already exists.&#x000D;&#x000A;   at System.Collections.Specialized.ListDictionary.Add(Object key, Object value)&#x000D;&#x000A;   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.ShimCompletionSessionExtensions.ToLegacy(IAsyncCompletionSession session, SnapshotPoint triggerLocation)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.CreateCompletionSession(ITextView textView, ITrackingPoint triggerPoint, Boolean trackCaret)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Completion.CompletionController.TriggerCompletion()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Completion.CompletionController.ShowCompletion(Boolean autoShownCompletion)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Completion.CompletionController.OnPostTypeChar(Char typedCharacter)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Html.Editor.Completion.HtmlCompletionController.OnPostTypeChar(Char typedCharacter)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Completion.TypingCommandHandler.OnPostTypeChar(Char typedChar)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Completion.TypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Html.Editor.Commands.HtmlTypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Controller.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Html.Editor.Commands.HtmlMainController.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Interop.CommandTargetToOleShim.Exec(Guid&amp; guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```
 * Try using the cursors to select an item from the completion list. First, it shows *two* separate completion lists next to each other. Then, when you press enter, it ignores the item you chose, and uses the first one that was previously highlighted! Example where I try to pick `onblur` but it completes as `onabort`:

![capture](https://user-images.githubusercontent.com/1101362/58956541-76d49c00-8796-11e9-8ab8-84051f72cba9.gif)

Note: This is all using VS 29004.115.d16.2 (i.e., int.d16.2 channel)

**Comment by rynowak** [comment]
@NTaylorMullen - which ones of these are the issues that are already being worked on?

**Comment by NTaylorMullen** [comment]
All of the above completion issues will be fixed by @amadeusw's VS insertion and the formatting one will be fixed by @ToddGrun's insertion. 

So, these are all known and are pending insertions into VS. I still plan to update the dogfood alias for when we have a viable VS build, stay tuned!

**Comment by NTaylorMullen** [comment]
Oh and the exception one is also fixed by @AmadeusW's changes.

**Comment by SteveSandersonMS** [comment]
That's great to hear!

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS I marked this as done, if you could close this once you've verified everything on your end now works that'd be great!

**Comment by SteveSandersonMS** [comment]
I got the latest d16.2 today (29006.145.d16.2), and most of these do appear to be fixed :)

However,

* Typing `<div @bind=` still gets transformed into `<div @bind-=""`
* Pasting markup that contains `@bind=` still adds a space between `@bind` and `=` **if** you do it sufficiently quickly after first creating the `.razor` files. On my machine, when you create a new `.razor` file using the item template, there's a period of at least 5 seconds before VS starts applying Razor conventions to it. If you paste anything during that period, you get the extra space inserted (plus of course none of the tag helpers light up). Is this expected? Is there any easy fix?

**Comment by SteveSandersonMS** [comment]
Assigning back to Taylor for comments. The remaining issues are pretty minor at this stage. Thanks for fixing the major ones!

**Comment by NTaylorMullen** [comment]
> * Typing `<div @bind=` still gets transformed into `<div @bind-=""`

Isn't that expected? I don't believe there is an `@bind` on div so it does the only completion that makes sense `@bind-`

> * Pasting markup that contains `@bind=` still adds a space between `@bind` and `=` **if** you do it sufficiently quickly after first creating the `.razor` files. On my machine, when you create a new `.razor` file using the item template, there's a period of at least 5 seconds before VS starts applying Razor conventions to it. If you paste anything during that period, you get the extra space inserted (plus of course none of the tag helpers light up). Is this expected? Is there any easy fix?

There's not much here we can do sadly because the system doesn't yet understand the valid components in the file (or even if it is a component) and therefore tries to format the document as if `@bind` was an implicit expression. @bhsubra @ToddGrun how important is formatting implicit expressions by adding spaces like this? Aka, what scenarios does it enable?

**Comment by SteveSandersonMS** [comment]
> Isn't that expected? I don't believe there is an @bind on div so it does the only completion that makes sense @bind-

I agree it's an edge case. But I don't agree that `<div @bind-=""` *ever* makes sense. It's malformed.

I wouldn't consider it super high priority to do anything about this, except if it also repros in more common cases.

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT this doesn't meet the bar for preview7. Heck this could come in post-3.0 😄

**Comment by mkArtakMSFT** [comment]
I'm closing this now, given the scenario to be fixed is a corner case one.
